Repository schubergphilis/terraform-aws-mcaf-service-quotas-manager, pull requests merged in 2024-01, with the labels that each got.

#4 enhancement: Extend supported quotas
  service_quotas_manager/service_quotas_manager/custom_collection_queries.json
  service_quotas_manager/tests/conftest.py
  service_quotas_manager/tests/fixtures/custom_collection_queries.json
  service_quotas_manager/tests/test_custom_collection_queries.py
Labels: enhancement

#5 bug: fix unique bucket name requirements and set correct default role name
  README.md
  s3.tf
  variables.tf
Labels: bug

#6 bug: solve sns aws:SourceOwner deprecation
  examples/basic/main.tf
  examples/multi_account/main.tf
  examples/with_increase_config/main.tf
Labels: bug

#7 bug: fix inconsistent naming
  README.md
  lambda.tf
Labels: bug

#8 docs: document supported service quotas
  README.md
  SUPPORTED_QUOTAS.md
  docs/gen-supported-service-quotas.py
Labels: documentation

#9 bug: update s3 module to latest version to ensure compatibility with name_prefix
  README.md
  s3.tf
Labels: bug
